name: Deploy Web

on:
  push:
    tags:
      - '*'
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clone source code
        run: |
          git clone --depth=1 --branch=master https://devlaq:${{ secrets.API_TOKEN }}@github.com/EntropySystems/Web ./source

      - name: Run build
        run: |
          cd ./source
          npm install
          npm run build
          mv build ../build

      - name: Upload build files
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN }}
        with:
          source-directory: 'build'
          destination-github-username: 'EntropySystems'
          destination-repository-name: 'WebDeployment'
          user-email: devlaq4918@gmail.com
          target-branch: deployment